apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pc-daemonset
  namespace:  6lquan
spec:
  template:
    metadata:
      name: nginx-pod-Name
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.1
  selector:
    matchLabels:
      app: nginx-pod
