apiVersion: batch/v1
kind: Job
metadata:
  name: pc-job
  namespace: 6lquan
  labels:
    app: pc-job
spec:
  manualSelector: true  # 是否可以使用selector选择器选择pod，默认是false
  completions: 6 # 指定job需要成功运行Pods的次数。默认值: 1
  parallelism: 3 # 指定job在任一时刻应该并发运行Pods的数量。默认值: 1
  template:
    metadata:
      name: counter-pod-name
      labels:
        app: counter-pod
    spec:
      containers:
        - name: counter
          image: busybox:1.30
          command:
            - "bin/sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1; do echo $i;sleep 5;done"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never # 重启策略只能设置为Never或者OnFailure
  selector:
    matchLabels:
      app: counter-pod
