apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  pc-cronjob-name
  namespace: 6lquan
  labels:
    app: pc-cronjob
spec:
  schedule: "*/1 * * * *"  # cron格式的作业调度运行时间点，用于控制任务任务时间执行
  jobTemplate:  # job控制器模板，用于为cronjob控制器生成job对象，下面其实就是job的定义
    metadata: {}
    spec:
      template: # 模板，当副本数量不足时，会根据下面的模板创建Pod模板
        spec:
          restartPolicy: Never # 重启策略只能设置为Never或OnFailure
          containers:
            - name: counter
              image: busybox:1.30
              command: ["bin/sh","-c","for i in 9 8 7 6 5 4 3 2 1; do echo $i;sleep 3;done"]


