apiVersion: v1
kind: Namespace
metadata:
  name: springboot-ns  # namespace空间
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
  namespace: springboot-ns
  labels:
    app: springboot-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-pod
  template:
    metadata:
      name: springboot-pod-temp
      labels:
        app: springboot-pod
    spec:
      containers:
        - name: springboot-pod
          image: registry.cn-hangzhou.aliyuncs.com/lquan/lquandocker:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: springboot-ns
spec:
  selector:
    app: springboot-pod
  ports:
    - port: 8888
      targetPort: 8080
      nodePort: 30088
      protocol: TCP
  type: NodePort