apiVersion: v1
kind: Namespace
metadata:
  name: 5lquan


---
# 5.2.5 端口设置
  # 设置的containers的port选项的端口
apiVersion: v1
kind: Pod
metadata:
  name: pod-ports
  namespace: 5lquan
  labels:
    app: pod-ports
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP



