# 创建namespace
apiVersion: v1
kind: Namespace
metadata:
  name: 5lquan

---
#  5.2.4 环境变量
#env，环境变量，用于在pod中的容器设置环境变量。
apiVersion: v1
kind: Pod
metadata:
  name: pod-evn
  namespace: 5lquan
  labels:
    app: pod-evn-label
spec:
  containers:
    - name: busybox
      image: busybox:1.30
      command:
        - "/bin/sh"
        - "-c"
        - "while true;do /bin/echo $(date +%T);sleep 60; done;"
      env:
        - name: "userName"
          value: "admin"
        - name: "password"
          value: "123456"

