# 容器重启策略
apiVersion: v1
kind: Namespace
metadata:
  name: 5lquan
  
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-restartpolicy
  namespace: 5lquan
  labels:
    app: pod-restartpolicy-label
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      ports:
        - containerPort: 80
          name: nginx-port
      livenessProbe:
        httpGet:
          port: 80
          scheme: HTTP
          path: /hello
      imagePullPolicy: IfNotPresent
  restartPolicy: Never

