apiVersion: v1
kind: Namespace
metadata:
  name: 5lquan


---
# 初始化容器
apiVersion: v1
kind: Pod
metadata:
  name: pod-initcontainer
  namespace: 5lquan
  labels:
    app: pod-initcontainer-label
spec:
  containers:
  - name: main-container
    image: nginx:1.17.1
    ports:
    - name: nginx-port
      containerPort: 80
  initContainers:
  - name: test-k8s-node01
    image: busybox:1.30
    command:
      - "sh"
      - "-c"
      - "until ping 192.168.254.87 -c 1 ; do echo waiting for mysql... >>/tmp/lquan.log; sleep 2; done;"

