# Pod调度 亲和性调度-requiredDuringSchedulingIgnoredDuringExecution 软限制
apiVersion: v1
kind: Namespace
metadata:
  name: 5lquan
  
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeaffinity-preferred
  namespace: 5lquan
  labels:
    app: pod-nodeaffinity-preferred-labels
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      ports:
        - containerPort: 80
          name: nginx-port
  affinity:  #亲和性设置
    nodeAffinity: #设置node亲和性
      preferredDuringSchedulingIgnoredDuringExecution:  # 软限制
        - preference:
            matchExpressions: # 匹配env的值在["xxx","yyy"]中的标签(当前环境没有)
              - key: nodeenv
                operator: In
                values:
                  - "xxx"
                  - "yyy"
          weight: 1


