#pod的亲和性调度requiredDuringSchedulingIgnoredDuringExecution 
apiVersion: v1
kind: Namespace
metadata:
  name: 5lquan
  
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeaffinity-required
  namespace: 5lquan
  labels:
    app: pod-nodeaffinity-required-label
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
  affinity:   #亲和性设置
    nodeAffinity:  #设置node亲和性
      requiredDuringSchedulingIgnoredDuringExecution: #设置node亲和性
        nodeSelectorTerms:
          - matchExpressions:  # 匹配env的值在["xxx","yyy"]中的标签
              - key: nodeenv
                operator: In
                values: ["xxx","yyy"]



