apiVersion: v1
kind: Pod
metadata:
  name: "pod5.1.1"
  namespace: 5lquan
  labels:
    version: "1.0"
spec:
  containers:
  - name: nginxlquan51-con
    image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    env:
    - name: "username"
      value: "admin"
    - name: "passwd"
      value: "123456"
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"

    ports: #设置容器暴露的端口列表
    - name: nginx-port
      containerPort: 80
      protocol: TCP
