# 根据pv去创建pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: 8lquan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
  namespace: 8lquan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc3
  namespace: 8lquan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
