#创建secret
apiVersion: v1
kind: Secret
metadata:
  name: secretlquan
  namespace: 8lquan
type: Opaque
data:
  username: YWRtaW4=
  passsword: MTIzNDU2


---

#创建pod
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: 8lquan
  labels:
    app: pod-secret
spec:
  containers:
    - name: pod-secret
      image: nginx:1.17.1
      imagePullPolicy: IfNotPresent
      volumeMounts: # 将secret挂载到目录上
        - mountPath: /secret/config
          name: configxx

  volumes:
    - name: configxx
      secret:
        secretName: secretlquan
